statDefinition = {"Acceleration": "Acc",
                  "Agility": "Agi",
                  "Balance": "Bal",
                  "Jumping Reach": "Jum",
                  "Natural Fitness": "Nat",
                  "Pace": "Pac",
                  "Stamina": "Sta",
                  "Strength": "Str",
                  "Aerial Ability": "Aer",
                  "Aggression": "Agg",
                  "Anticipation": "Ant",
                  "Bravery": "Bra",
                  "Command of the Area": "Cmd",
                  "Communication": "Com",
                  "Composure": "Cmp",
                  "Concentration": "Cnt",
                  "Corners": "Cor",
                  "Crossing": "Cro",
                  "Decision": "Dec",
                  "Determination": "Det",
                  "Dribbling": "Dri",
                  "Eccentricity": "Ecc",
                  "Finishing": "Fin",
                  "First Touch": "Fir",
                  "Flair": "Fla",
                  "Free Kicks": "Fre",
                  "Handling": "Han",
                  "Heading": "Hea",
                  "Kicking": "Kic",
                  "Leadership": "Ldr",
                  "Long Shots": "Lon",
                  "Long Throws": "L Th",
                  "Marking": "Mar",
                  "Off the Ball": "OtB",
                  "One v Ones": "1v1",
                  "Passing": "Pas",
                  "Penalties": "Pen",
                  "Positioning": "Pos",
                  "Reflexes": "Ref",
                  "Rushing Out": "Rus",
                  "Tackling": "Tck",
                  "Teamwork": "Tea",
                  "Technique": "Tec",
                  "Tendency to Punch": "Pun",
                  "Throwing": "Thr",
                  "Vision": "Vis",
                  "Work Rate": "Wor"
                  }
